### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by tstanciu** [fr0tt/benotes#69]
Login not working. I installed the application with docker and executed the two commands:

- php artisan migrate
- php artisan install --only-user

![image](https://user-images.githubusercontent.com/63559907/230867966-3c5fe341-bd83-436e-81f2-c9d7b51283f9.png)

I have attached the logs from the container: [_benotes_logs.txt](https://github.com/fr0tt/benotes/files/11189185/_benotes_logs.txt)

I reinstalled the application from scratch several times, but every time I got stuck at this point.

**Comment by fr0tt** [comment]
Did you encounter any error messages while executing those two commands ?
Is there anything of value in the storage/logs/laravel.log file ?

**Comment by tstanciu** [comment]
Initially, I built my docker-compose file and received the above error.
```
version: "3.9"
services:
  benotes:
    image: fr0tt/benotes
    container_name: benotes
    environment:
      - APP_NAME=Benotes
      - APP_ENV=development
      - APP_DEBUG=true
      - APP_URL=http://localhost:8001
      - APP_KEY=RNUVfISsdvwHlJ3nqzUPW8yVQKzYK78n7wG0ZieA8+s=
      - JWT_SECRET=Jpoh+76cW49gyX2aOQeJnOL2wOc+I8xJmkhUIO/Yd1Y=
      - USE_FILESYSTEM=true
      - RUN_MIGRATIONS=false
      - DB_CONNECTION=sqlite
      - DB_HOST=
      - DB_PORT=
      - DB_DATABASE=storage/database.sqlite
      - DB_USERNAME=
      - DB_PASSWORD=
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - MAIL_DRIVER=smtp
      - MAIL_HOST=
      - MAIL_PORT=587
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=
      - MAIL_FROM_NAME="Benotes"
    volumes:
      - benotes_storage:/var/www/storage
      - benotes_nginx_logs:/var/lib/nginx/logs
    ports:
      - 8001:80
volumes:
  benotes_storage:
  benotes_nginx_logs:
```

After that I followed the steps from here https://benotes.org/docs/installation/docker-compose and everything worked. I will close the ticket. Thank you
